import { useState, useEffect } from 'react';
import { FileText, Plus, Edit, Trash2, Search, Filter, Check, X } from 'lucide-react';
import Navigation from '../components/Navigation.component';

export default function AdminContractTemplates() {
  const [templates, setTemplates] = useState([]);
  const [contractTypes, setContractTypes] = useState([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState('');
  const [filterType, setFilterType] = useState('');
  const [filterAvailable, setFilterAvailable] = useState('');
  const [showModal, setShowModal] = useState(false);
  const [editingTemplate, setEditingTemplate] = useState(null);
  const [user, setUser] = useState(null);

  const [formData, setFormData] = useState({
    contract_type_id: '',
    version: '',
    description: '',
    contract_period: '',
    first_payment_months: '',
    payment_interval: 'monthly',
    unit_amount: '',
    monthly_payment_amount: '',
    other_support_amount: '',
    required_fields: [],
    field_rules: {},
    memo: '',
    template_file_url: '',
    pdf_file_path: '',
    is_available: true
  });
  const [uploadedPdfFile, setUploadedPdfFile] = useState(null);

  useEffect(() => {
    const userData = JSON.parse(localStorage.getItem('user'));
    setUser(userData);
    fetchTemplates();
    fetchContractTypes();
  }, []);

  const fetchTemplates = async () => {
    try {
      const response = await fetch('${import.meta.env.VITE_API_URL}/api/contract-templates');
      
      if (!response.ok) {
        throw new Error('?úÌîåÎ¶?Ï°∞Ìöå ?§Ìå®');
      }
      
      const data = await response.json();
      setTemplates(data || []);
    } catch (error) {
      setTemplates([]);
    } finally {
      setLoading(false);
    }
  };

  const fetchContractTypes = async () => {
    try {
      const response = await fetch('${import.meta.env.VITE_API_URL}/api/contract-types');
      
      if (!response.ok) {
        throw new Error('Í≥ÑÏïΩÏ¢ÖÎ•ò Ï°∞Ìöå ?§Ìå®');
      }
      
      const data = await response.json();
      setContractTypes(data.types || []);
    } catch (error) {
      setContractTypes([]);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    
    console.log('=== ?úÌîåÎ¶??Ä???úÏûë ===');
    console.log('formData:', formData);
    
    try {
      // PDF ?åÏùº???àÏúºÎ©?Î®ºÏ? ?ÖÎ°ú??
      let pdfFilePath = formData.pdf_file_path;
      if (uploadedPdfFile) {
        const fileFormData = new FormData();
        fileFormData.append('pdf', uploadedPdfFile);
        
        const uploadResponse = await fetch('${import.meta.env.VITE_API_URL}/api/contract-templates/upload-pdf', {
          method: 'POST',
          body: fileFormData
        });
        
        if (uploadResponse.ok) {
          const uploadData = await uploadResponse.json();
          pdfFilePath = uploadData.filePath;
        } else {
          alert('PDF ?åÏùº ?ÖÎ°ú?úÏóê ?§Ìå®?àÏäµ?àÎã§.');
          return;
        }
      }
      
      // ?†ÌÉù??Í≥ÑÏïΩ ?Ä?ÖÏùò ÏΩîÎìú Ï∞æÍ∏∞
      const selectedType = contractTypes.find(t => t.id === parseInt(formData.contract_type_id));
      const typeCode = selectedType?.code || '';
      
      // ?úÌñâ?ºÏùÑ YYYYMMDD ?ïÏãù?ºÎ°ú Î≥Ä??
      const dateStr = formData.version.replace(/-/g, '');
      
      // ?úÌîåÎ¶øÎ™Ö ?êÎèô ?ùÏÑ±: Í≥ÑÏïΩ?Ä?ÖÏΩî??YYYYMMDD
      const autoGeneratedName = `${typeCode}_${dateStr}`;
      
      const payload = {
        contract_type_id: parseInt(formData.contract_type_id),
        version: formData.version,
        name: autoGeneratedName,
        description: formData.description || null,
        contract_period: formData.contract_period ? parseInt(formData.contract_period) : null,
        first_payment_months: formData.first_payment_months ? parseInt(formData.first_payment_months) : null,
        payment_interval: formData.payment_interval || null,
        unit_amount: formData.unit_amount !== '' ? parseInt(String(formData.unit_amount).replace(/,/g, '')) : null,
        monthly_payment_amount: formData.monthly_payment_amount !== '' ? parseInt(String(formData.monthly_payment_amount).replace(/,/g, '')) : null,
        other_support_amount: formData.other_support_amount !== '' ? parseInt(String(formData.other_support_amount).replace(/,/g, '')) : 0,
        required_fields: formData.required_fields || [],
        field_rules: formData.field_rules || {},
        memo: formData.memo || null,
        template_file_url: formData.template_file_url || null,
        pdf_file_path: pdfFilePath || null,
        is_available: formData.is_available,
        effective_date: formData.version,
        created_by: user?.id,
        changed_by: user?.id
      };

      console.log('?úÌîåÎ¶??Ä??payload:', payload);

      const url = editingTemplate
        ? `${import.meta.env.VITE_API_URL}/api/contract-templates/${editingTemplate.id}`
        : '${import.meta.env.VITE_API_URL}/api/contract-templates';
      
      const method = editingTemplate ? 'PUT' : 'POST';
      
      console.log('?îÏ≤≠ URL:', url);
      console.log('?îÏ≤≠ Method:', method);

      const response = await fetch(url, {
        method,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      });

      console.log('?ëÎãµ ?ÅÌÉú:', response.status);

      if (!response.ok) {
        const errorData = await response.json();
        console.log('?êÎü¨ ?ëÎãµ:', errorData);
        if (errorData.error?.includes('duplicate key')) {
          alert('?¥Î? Í∞ôÏ? Í≥ÑÏïΩ?Ä?ÖÍ≥º ?úÌñâ??Ï°∞Ìï©???úÌîåÎ¶øÏù¥ Ï°¥Ïû¨?©Îãà??');
        } else {
          alert('?úÌîåÎ¶??Ä?•Ïóê ?§Ìå®?àÏäµ?àÎã§: ' + (errorData.error || '?????ÜÎäî ?§Î•ò'));
        }
        return;
      }

      const result = await response.json();
      console.log('?Ä???±Í≥µ:', result);
      
      fetchTemplates();
      closeModal();
    } catch (error) {
      console.error('?Ä??Ï§??êÎü¨:', error);
      alert('?úÌîåÎ¶??Ä??Ï§??§Î•òÍ∞Ä Î∞úÏÉù?àÏäµ?àÎã§: ' + error.message);
    }
  };

  const handleDelete = async (id) => {
    if (!confirm('?ïÎßê ??†ú?òÏãúÍ≤†Ïäµ?àÍπå?')) return;

    try {
      const response = await fetch(`${import.meta.env.VITE_API_URL}/api/contract-templates/${id}`, {
        method: 'DELETE',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ changed_by: user?.id })
      });

      if (response.ok) {
        fetchTemplates();
      }
    } catch (error) {
    }
  };

  const toggleAvailability = async (template) => {
    try {
      const response = await fetch(`${import.meta.env.VITE_API_URL}/api/contract-templates/${template.id}/availability`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          is_available: !template.is_available,
          changed_by: user?.id
        })
      });

      if (response.ok) {
        fetchTemplates();
      }
    } catch (error) {
    }
  };

  const openEditModal = (template) => {
    setEditingTemplate(template);
    setFormData({
      contract_type_id: template.contract_type_id,
      version: template.effective_date,
      description: template.description || '',
      contract_period: template.contract_period || '',
      first_payment_months: template.first_payment_months || '',
      payment_interval: template.payment_interval || 'monthly',
      unit_amount: template.unit_amount ?? '',
      monthly_payment_amount: template.monthly_payment_amount ?? '',
      other_support_amount: template.other_support_amount ?? '',
      required_fields: template.required_fields || [],
      field_rules: template.field_rules || {},
      memo: template.memo || '',
      template_file_url: template.template_file_url || '',
      pdf_file_path: template.pdf_file_path || '',
      is_available: template.is_available
    });
    setUploadedPdfFile(null);
    setShowModal(true);
  };

  const closeModal = () => {
    setShowModal(false);
    setEditingTemplate(null);
    setUploadedPdfFile(null);
    setFormData({
      contract_type_id: '',
      version: '',
      description: '',
      contract_period: '',
      first_payment_months: '',
      payment_interval: 'monthly',
      unit_amount: '',
      monthly_payment_amount: '',
      other_support_amount: '',
      required_fields: [],
      field_rules: {},
      memo: '',
      template_file_url: '',
      pdf_file_path: '',
      is_available: true
    });
  };

  const filteredTemplates = Array.isArray(templates) ? templates.filter(template => {
    const matchesSearch = template.effective_date?.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         template.contract_types?.name?.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesType = !filterType || template.contract_type_id === parseInt(filterType);
    const matchesAvailable = filterAvailable === '' || template.is_available === (filterAvailable === 'true');
    
    return matchesSearch && matchesType && matchesAvailable;
  }) : [];

  if (loading) {
    return <div className="flex justify-center items-center min-h-screen">Î°úÎî©Ï§?..</div>;
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <Navigation />

      <div className="max-w-7xl mx-auto px-4 py-6">
        {/* Í≤Ä??Î∞??ÑÌÑ∞ */}
        <div className="bg-white rounded-lg shadow-sm p-4 mb-6">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
            <div className="relative">
              <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" size={20} />
              <input
                type="text"
                placeholder="?úÌîåÎ¶?Í≤Ä??.."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="w-full pl-10 pr-4 py-2 border rounded-lg focus:outline-none focus:ring-2"
                style={{ fontSize: '15px' }}
              />
            </div>

            <select
              value={filterType}
              onChange={(e) => setFilterType(e.target.value)}
              className="px-4 py-2 border rounded-lg focus:outline-none focus:ring-2"
              style={{ fontSize: '15px' }}
            >
              <option value="">Î™®Îì† Í≥ÑÏïΩ ?Ä??/option>
              {Array.isArray(contractTypes) && contractTypes.map(type => (
                <option key={type.id} value={type.id}>{type.name}</option>
              ))}
            </select>

            <select
              value={filterAvailable}
              onChange={(e) => setFilterAvailable(e.target.value)}
              className="px-4 py-2 border rounded-lg focus:outline-none focus:ring-2"
              style={{ fontSize: '15px' }}
            >
              <option value="">?†ÌÉù Í∞Ä???¨Î?</option>
              <option value="true">?†ÌÉù Í∞Ä??/option>
              <option value="false">?†ÌÉù Î∂àÍ?</option>
            </select>

            <button
              onClick={() => setShowModal(true)}
              className="flex items-center justify-center gap-2 px-4 py-2 text-white rounded-lg hover:opacity-90 transition-opacity"
              style={{ backgroundColor: '#249689', fontSize: '15px' }}
            >
              <Plus size={20} />
              ???úÌîåÎ¶??±Î°ù
            </button>
          </div>
        </div>

        {/* ?úÌîåÎ¶?Î™©Î°ù */}
        <div className="bg-white rounded-lg shadow-sm overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead style={{ backgroundColor: '#f0fdfa' }}>
                <tr>
                  <th className="px-4 py-3 text-left font-semibold" style={{ color: '#115e59', fontSize: '14px' }}>Í≥ÑÏïΩ ?Ä??/th>
                  <th className="px-4 py-3 text-left font-semibold" style={{ color: '#115e59', fontSize: '14px' }}>?úÌñâ??/th>
                  <th className="px-4 py-3 text-left font-semibold" style={{ color: '#115e59', fontSize: '14px' }}>Í≥ÑÏïΩÍ∏∞Í∞Ñ</th>
                  <th className="px-4 py-3 text-left font-semibold" style={{ color: '#115e59', fontSize: '14px' }}>Ï≤´Ï?Í∏?/th>
                  <th className="px-4 py-3 text-center font-semibold" style={{ color: '#115e59', fontSize: '14px' }}>?†ÌÉùÍ∞Ä??/th>
                  <th className="px-4 py-3 text-center font-semibold" style={{ color: '#115e59', fontSize: '14px' }}>Í¥ÄÎ¶?/th>
                </tr>
              </thead>
              <tbody>
                {filteredTemplates.length === 0 ? (
                  <tr>
                    <td colSpan="6" className="px-4 py-8 text-center text-gray-500" style={{ fontSize: '15px' }}>
                      ?±Î°ù???úÌîåÎ¶øÏù¥ ?ÜÏäµ?àÎã§.
                    </td>
                  </tr>
                ) : (
                  filteredTemplates.map((template) => (
                    <tr key={template.id} className="border-t hover:bg-gray-50">
                      <td className="px-4 py-3" style={{ fontSize: '15px' }}>
                        {template.contract_types?.name}
                      </td>
                      <td className="px-4 py-3" style={{ fontSize: '15px' }}>
                        {template.effective_date}
                      </td>
                      <td className="px-4 py-3" style={{ fontSize: '15px' }}>
                        {template.contract_period ? `${template.contract_period}Í∞úÏõî` : '-'}
                      </td>
                      <td className="px-4 py-3" style={{ fontSize: '15px' }}>
                        {template.first_payment_months ? `${template.first_payment_months}Í∞úÏõî ?? : '-'}
                      </td>
                      <td className="px-4 py-3 text-center">
                        <button
                          onClick={() => toggleAvailability(template)}
                          className={`p-1 rounded ${template.is_available ? 'text-green-600' : 'text-red-600'}`}
                        >
                          {template.is_available ? <Check size={20} /> : <X size={20} />}
                        </button>
                      </td>
                      <td className="px-4 py-3">
                        <div className="flex items-center justify-center gap-2">
                          <button
                            onClick={() => openEditModal(template)}
                            className="p-1 hover:bg-gray-100 rounded"
                            style={{ color: '#249689' }}
                          >
                            <Edit size={18} />
                          </button>
                          <button
                            onClick={() => handleDelete(template.id)}
                            className="p-1 text-red-600 hover:bg-red-50 rounded"
                          >
                            <Trash2 size={18} />
                          </button>
                        </div>
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </div>
      </div>

      {/* ?±Î°ù/?òÏ†ï Î™®Îã¨ */}
      {showModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-lg w-full max-w-3xl max-h-[90vh] overflow-y-auto">
            <div className="sticky top-0 bg-white border-b px-6 py-4 flex items-center justify-between">
              <h2 className="text-lg font-bold" style={{ color: '#249689' }}>
                <FileText className="inline mr-2" size={20} />
                {editingTemplate ? '?úÌîåÎ¶??òÏ†ï' : '???úÌîåÎ¶??±Î°ù'}
              </h2>
              <button onClick={closeModal} className="text-gray-500 hover:text-gray-700">
                <X size={24} />
              </button>
            </div>

            <form onSubmit={handleSubmit} className="p-6 space-y-4">
              {/* Ï≤?Î≤àÏß∏ Ï§? Í≥ÑÏïΩ?Ä??/ ?úÌñâ??*/}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-semibold mb-2" style={{ color: '#115e59' }}>
                    Í≥ÑÏïΩ ?Ä??*
                  </label>
                  <select
                    value={formData.contract_type_id}
                    onChange={(e) => setFormData({ ...formData, contract_type_id: e.target.value })}
                    className="w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2"
                    style={{ fontSize: '15px' }}
                    required
                  >
                    <option value="">?†ÌÉù?òÏÑ∏??/option>
                    {Array.isArray(contractTypes) && contractTypes.map(type => (
                      <option key={type.id} value={type.id}>{type.name}</option>
                    ))}
                  </select>
                </div>

                <div>
                  <label className="block text-sm font-semibold mb-2" style={{ color: '#115e59' }}>
                    ?úÌñâ??*
                  </label>
                  <input
                    type="date"
                    value={formData.version}
                    onChange={(e) => setFormData({ ...formData, version: e.target.value })}
                    className="w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2"
                    style={{ fontSize: '15px' }}
                    required
                  />
                </div>
              </div>

              {/* ?§Î™Ö */}
              <div>
                <label className="block text-sm font-semibold mb-2" style={{ color: '#115e59' }}>
                  ?§Î™Ö
                </label>
                <textarea
                  value={formData.description}
                  onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                  className="w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2"
                  style={{ fontSize: '15px', minHeight: '80px' }}
                  placeholder="?úÌîåÎ¶??§Î™Ö"
                />
              </div>

              {/* Í≥ÑÏïΩÍ∏∞Í∞Ñ / Ï≤´Ï?Í∏âÏùº / ÏßÄÍ∏âÏ£ºÍ∏?*/}
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <div>
                  <label className="block text-sm font-semibold mb-2" style={{ color: '#115e59' }}>
                    Í≥ÑÏïΩÍ∏∞Í∞Ñ (Í∞úÏõî)
                  </label>
                  <input
                    type="number"
                    value={formData.contract_period}
                    onChange={(e) => setFormData({ ...formData, contract_period: e.target.value })}
                    className="w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2"
                    style={{ fontSize: '15px' }}
                    placeholder="24"
                  />
                </div>

                <div>
                  <label className="block text-sm font-semibold mb-2" style={{ color: '#115e59' }}>
                    Ï≤´Ï?Í∏âÏùº (Í∞úÏõî ??
                  </label>
                  <input
                    type="number"
                    value={formData.first_payment_months}
                    onChange={(e) => setFormData({ ...formData, first_payment_months: e.target.value })}
                    className="w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2"
                    style={{ fontSize: '15px' }}
                    placeholder="1"
                  />
                </div>

                <div>
                  <label className="block text-sm font-semibold mb-2" style={{ color: '#115e59' }}>
                    ÏßÄÍ∏âÏ£ºÍ∏?
                  </label>
                  <select
                    value={formData.payment_interval}
                    onChange={(e) => setFormData({ ...formData, payment_interval: e.target.value })}
                    className="w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2"
                    style={{ fontSize: '15px' }}
                  >
                    <option value="monthly">Îß§Ïõî</option>
                    <option value="quarterly">Î∂ÑÍ∏∞</option>
                    <option value="yearly">??/option>
                  </select>
                </div>
              </div>

              {/* 1Unit(?? / ÏßÄÍ∏âÏï°/Unit(?? / Í∏∞Ì?ÏßÄ?êÍ∏à */}
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <div>
                  <label className="block text-sm font-semibold mb-2" style={{ color: '#115e59' }}>
                    1Unit (??
                  </label>
                  <div className="relative">
                    <input
                      type="text"
                      value={formData.unit_amount != null && formData.unit_amount !== '' ? parseInt(formData.unit_amount).toLocaleString() : ''}
                      onChange={(e) => {
                        const value = e.target.value.replace(/,/g, '');
                        if (!isNaN(value)) {
                          setFormData({ ...formData, unit_amount: value });
                        }
                      }}
                      className="w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2"
                      style={{ fontSize: '15px', textAlign: 'right', paddingRight: '40px' }}
                      placeholder="30,000,000"
                    />
                    <span className="absolute right-3 top-1/2 transform -translate-y-1/2" style={{ color: '#6b7280', fontSize: '15px' }}>
                      ??
                    </span>
                  </div>
                </div>

                <div>
                  <label className="block text-sm font-semibold mb-2" style={{ color: '#115e59' }}>
                    ÏßÄÍ∏âÏï°/Unit (??
                  </label>
                  <div className="relative">
                    <input
                      type="text"
                      value={formData.monthly_payment_amount != null && formData.monthly_payment_amount !== '' ? parseInt(formData.monthly_payment_amount).toLocaleString() : ''}
                      onChange={(e) => {
                        const value = e.target.value.replace(/,/g, '');
                        if (!isNaN(value)) {
                          setFormData({ ...formData, monthly_payment_amount: value });
                        }
                      }}
                      className="w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2"
                      style={{ fontSize: '15px', textAlign: 'right', paddingRight: '40px' }}
                      placeholder="1,500,000"
                    />
                    <span className="absolute right-3 top-1/2 transform -translate-y-1/2" style={{ color: '#6b7280', fontSize: '15px' }}>
                      ??
                    </span>
                  </div>
                </div>

                <div>
                  <label className="block text-sm font-semibold mb-2" style={{ color: '#115e59' }}>
                    Í∏∞Ì?ÏßÄ?êÍ∏à (??
                  </label>
                  <div className="relative">
                    <input
                      type="text"
                      value={formData.other_support_amount != null && formData.other_support_amount !== '' ? parseInt(formData.other_support_amount).toLocaleString() : ''}
                      onChange={(e) => {
                        const value = e.target.value.replace(/,/g, '');
                        if (!isNaN(value)) {
                          setFormData({ ...formData, other_support_amount: value });
                        }
                      }}
                      className="w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2"
                      style={{ fontSize: '15px', textAlign: 'right', paddingRight: '40px' }}
                      placeholder="0"
                    />
                    <span className="absolute right-3 top-1/2 transform -translate-y-1/2" style={{ color: '#6b7280', fontSize: '15px' }}>
                      ??
                    </span>
                  </div>
                </div>
              </div>

              {/* Î©îÎ™® */}
              <div>
                <label className="block text-sm font-semibold mb-2" style={{ color: '#115e59' }}>
                  Î©îÎ™®
                </label>
                <textarea
                  value={formData.memo}
                  onChange={(e) => setFormData({ ...formData, memo: e.target.value })}
                  className="w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2"
                  style={{ fontSize: '15px', minHeight: '100px' }}
                  placeholder="Î©îÎ™®Î•??ÖÎ†•?òÏÑ∏??
                />
              </div>

              {/* Í≥ÑÏïΩ??PDF ?ÖÎ°ú??*/}
              <div>
                <label className="block text-sm font-semibold mb-2" style={{ color: '#115e59' }}>
                  Í≥ÑÏïΩ??PDF ?åÏùº
                </label>
                <div className="border-2 border-dashed rounded-lg p-4" style={{ borderColor: '#e5e7eb' }}>
                  <input
                    type="file"
                    accept=".pdf"
                    onChange={(e) => {
                      const file = e.target.files[0];
                      if (file && file.type === 'application/pdf') {
                        setUploadedPdfFile(file);
                      } else {
                        alert('PDF ?åÏùºÎß??ÖÎ°ú??Í∞Ä?•Ìï©?àÎã§.');
                        e.target.value = '';
                      }
                    }}
                    className="w-full"
                    style={{ fontSize: '15px' }}
                  />
                  {uploadedPdfFile && (
                    <p className="text-sm mt-2" style={{ color: '#10b981' }}>
                      ??{uploadedPdfFile.name}
                    </p>
                  )}
                  {!uploadedPdfFile && formData.pdf_file_path && (
                    <p className="text-sm mt-2" style={{ color: '#6b7280' }}>
                      Í∏∞Ï°¥ ?åÏùº: {formData.pdf_file_path.split('/').pop()}
                    </p>
                  )}
                </div>
              </div>

              {/* ?†ÌÉù Í∞Ä??*/}
              <div className="flex items-center gap-2">
                <input
                  type="checkbox"
                  id="is_available"
                  checked={formData.is_available}
                  onChange={(e) => setFormData({ ...formData, is_available: e.target.checked })}
                  className="w-4 h-4"
                />
                <label htmlFor="is_available" className="text-sm font-semibold" style={{ color: '#115e59' }}>
                  ?†ÌÉù Í∞Ä??
                </label>
              </div>

              <div className="flex justify-end gap-3 pt-4 border-t">
                <button
                  type="button"
                  onClick={closeModal}
                  className="px-6 py-2 border rounded-lg hover:bg-gray-50"
                  style={{ fontSize: '15px' }}
                >
                  Ï∑®ÏÜå
                </button>
                <button
                  type="submit"
                  className="px-6 py-2 text-white rounded-lg hover:opacity-90"
                  style={{ backgroundColor: '#249689', fontSize: '15px' }}
                >
                  {editingTemplate ? '?òÏ†ï' : '?±Î°ù'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}